# Generated by Django 5.0.6 on 2024-06-20 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inventory_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
