# Generated by Django 5.0.6 on 2024-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inventory_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ManyToManyField(related_name='items', to='app.supplier'),
        ),
    ]
