# Generated by Django 5.0.6 on 2024-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_inventory_supplier_supplier_item_supplied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=None, max_length=30),
        ),
    ]
