# Generated by Django 5.0.6 on 2024-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
