# Generated by Django 5.0.6 on 2024-06-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=None, max_length=30),
        ),
    ]
