# Generated by Django 5.0.6 on 2024-06-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_supplier_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
